# Puppet Forge Address
forge "http://forge.puppetlabs.com"

# Modules from the Puppet Forge
mod "croddy/make"
mod "cvquesty/puppetdev"
mod "gentoo/portage"
mod "hunner/hiera"
mod "puppetlabs/apache"
mod "puppetlabs/apt"
mod "puppetlabs/concat"
mod "puppetlabs/gcc"
mod "puppetlabs/git"
mod "puppetlabs/inifile"
mod "puppetlabs/passenger"
mod "puppetlabs/pe_gem"
mod "puppetlabs/ruby"
mod "puppetlabs/stdlib"
mod "puppetlabs/vcsrepo"
mod "stahnma/epel"
mod "unibet/forge_server"
mod "saz/resolv_conf"
mod "zack/r10k"
